# 4. NumPy
---

In [1]:
import numpy as np

### 4.1 Одномерный массив

In [2]:
x = [2, 3, 4, 6]
y = np.array(x)
print(y)
print(y.shape)

[2 3 4 6]
(4,)


Срезы

In [3]:
print(y[1:3])

[3 4]


Вывод элементов по индексу

In [4]:
print(y[[0, 2]])

[2 4]


Логическая индексация

In [5]:
print(y[y>3])

[4 6]


Поэлементные операции над массивами: умножение, возведение в степень

In [6]:
print(y * 5)

[10 15 20 30]


In [7]:
print(y ** 2)

[ 4  9 16 36]


### 4.2 Двумерный массив

In [8]:
matrix = [[1, 2, 4], [3, 1, 0], [6, 8, 9]]
nd_array = np.array(matrix)

Вывод элемента двумерного массива

In [9]:
print(nd_array[1][2])

0


In [10]:
print(nd_array[1, 2])

0


Вывод отдельных строк массива

In [11]:
print(nd_array[1:3])

[[3 1 0]
 [6 8 9]]


### 4.3 Генератор случайных чисел

Генератор дробных случайных чисел из __равномерного распределения__

In [12]:
print(np.random.rand())

0.7487130774137376


Генератор случайных чисел из __нормального распределения__

In [13]:
print(np.random.randn())

0.19761469266228596


In [14]:
# Одномерный массив случайных чисел нормального распределения
print(np.random.randn(4))

[-0.20829346 -2.18121261 -1.31757313 -0.56402223]


In [15]:
# Двумерный массив случайных чисел нормального распределения
print(np.random.randn(4, 5))

[[-0.52435164  0.20079465 -2.08641498 -0.16249767  0.5481657 ]
 [-1.02386755  0.18060887  1.18553619 -1.33405396 -0.17340275]
 [ 0.27965007  1.17115234 -0.08109277  2.41405964 -0.47884284]
 [-1.63120656  0.93797994  0.7174813  -0.12038591 -0.03449094]]


Функция __`arange()`__ - аналог функции `range()`, генерирующий одномерный массив данных с заданным шагом (не обязательно целочисленным, в отличие от `range()`)

In [16]:
print(np.arange(0, 8, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
