# Всякая полезная мелочь
---

'\t' - табуляция

'\t' * 2 - две табуляции

\n - символ переноса строки

### Операторы continue, break

Оператор __`break`__ досрочно прерывает цикл.

Опертор __`continue`__ начинает следующий проход цикла, минуя оставшееся тело цикла.

In [1]:
s = 0

while True: # Это условие выполняется всегда
    s += 1
    if s % 2 == 0: # Через раз
        print('Continue') # вместо s будет выведено 'continue'
        continue # и код ниже в таком случае не будет исполнен в этой итерации
    print(s)
    if s > 10:# С помощью этой конструкции
        break # бесконечный цикл досрочно прерывается

1
Continue
3
Continue
5
Continue
7
Continue
9
Continue
11


### Тернарная операция

Присвоить x значение 10, если y больше 3 и 20 в противном случае

In [4]:
y = 15
x = 10 if y > 3 else 20

### pprint
Метод .pprint() выводит любую структуру данных в удобном для чтения формате

In [ ]:
import pprint
pprint.pprint()

### Округление float до n знаков после запятой

In [ ]:
variable = 100/12
n = 3

round(variable, n)

### Библиотека math

In [ ]:
from math import factorial
print('3! =', factorial(3))

### f-строки (python 3.6 +)

In [1]:
name = 'Fred'
seven = 7
print(f'He said his name is {name} and he is {6 * seven} years old.')

He said his name is Fred and he is 42 years old.


In [2]:
name = 'Fred'
age = 42
print('He said his name is {name} and he is {age} years old.'.format(name=name, age=age))

He said his name is Fred and he is 42 years old.


In [3]:
alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']

for i, (a, b) in enumerate(zip(alist, blist)):
    print (i, a, b)

0 a1 b1
1 a2 b2
2 a3 b3


In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix, '\n')

# Среднее по строкам
print(matrix.mean(axis = 1))

# Среднее по столбцам
print(matrix.mean(axis = 0))

# axis=1 означает усреднение по строчкам, axis=0 - усреднение по столбцам

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[2. 5. 8.]
[4. 5. 6.]
